### ISSUE TITLE
unable to have more then 2 homes

### ISSUE THREAD

**Issue by darkcamo12** [Thutmose/ThutEssentials#108]
#### Issue Description:
Setting "maxHomes =" to any number fails to take effect

#### What happens:
tried changing "maxHomes = 2" to a higher number like "9" while also adding "thutessentials.homes.max.9" to a random group in thutperms (one i was in), made 2 homes and tried to make a third and was unable to.

#### What you expected to happen:
add more homes for players

#### Steps to reproduce:

1.make new server running forge-1.16.4-35.1.36
2.add thutessentials and thutperms
3.change homes once the config is generated
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- thutessentials-1.16.4-4.1.4
- Minecraft: 1.16.4
- forge-1.16.4-35.1.36
- thutperms-1.16.4-4.0.0.b

Logs
ThutEssentials: https://pastebin.com/b0nAkL1w
ThutPerms: https://pastebin.com/Pbdng2g6
any other logs needed just ask

**Comment by Thutmose** [comment]
Can you do `/list_perms`, and then include the thutperms.log that it makes after that?

**Comment by darkcamo12** [comment]
with running ```/list_perms```
before updating mod 
ThutPerms: https://pastebin.com/A7uPzpMq

after getting the update from discord
ThutPerms: https://pastebin.com/83fJ9qrL
ThutEssentials: https://pastebin.com/UaCS6baG

**Comment by Thutmose** [comment]
hmm, it is only maintaining 2 homes as registered, can you confirm that the thutessentials config still has the larger number in it?

**Comment by darkcamo12** [comment]
changed it to 10 and when reading the thutessentials.log i see "Set maxHomes to 10" ( https://pastebin.com/ZFu8yUQr )

but you dont see that in the thutperms logfile ( https://pastebin.com/9hk5315L )

**Comment by Thutmose** [comment]
Ahh, I think I know what is going on, I sent another testing jar over discord, let me know how that one does?

**Comment by darkcamo12** [comment]
i can now see the permissions nodes showing up but regardless of which one i give a group i get the message in game of "You may not have that many homes!"

**Comment by darkcamo12** [comment]
This issue is fixed now

Thanks thutmose for all the help and hard work you have done
