### ISSUE TITLE
/spawn across dims disco's user and prevents relogging until after reboot

### ISSUE THREAD

**Issue by xenoflot** [Thutmose/ThutEssentials#11]
Server doesn't crash but the user who tried to /spawn home from nether or mining world can't get back in until the server is rebooted. 
Log extract: http://pastebin.com/U5rmezX7

Full log: http://xenoflot.com/logs/fml-server-latest.zip

**Comment by Thutmose** [comment]
Try updating, this was fixed in the latest versions.

**Comment by xenoflot** [comment]
/facepalm

I should've known that. Thanks!
