### ISSUE TITLE
spawnDefuzz ignores alternate World Generators

### ISSUE THREAD

**Issue by leagris** [Thutmose/ThutEssentials#14]
### Versions

- Minecraft Forge: 13.20.0.2282
- Thut Essentials: 1.6.8
- Realistic Terrain Generation: 5.1.0.0-alpha.1
- [Full modlist](https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/blob/master/modlist.md)

### Description

Spawn Defuzz causes players to spawn inside terrain when, World Generator is not default vanilla one.

### Reproduce

1. Install Thut Essentials with default settings to `spawnDefuzz=true` and an alternate world generator.
2. Generate new world
3. Good chances to spawn below surface inside terrain.

### Possible cause

The Defuzz computes Spawn Location based on vanilla terrain generation so, if a custom terrain generator generates a higher elevation, the `y` spawn height is likely to be inside terrain blocks below the surface.

### Work-around issue
Work-around with `spawnDefuzz=false` in [config/thutessentials.cfg](https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/commit/ab37682e913c7c7135e07a66c75c4ae2b50413d4)

**Comment by Thutmose** [comment]
it actually checks the world.getSpawnPoint(), I bet that is being set at some point below the surface, I didn't have it do any validation checks as to make it a lighter mod, it isn't intended for use on single player, but for use on servers where the server admin has use /setworldspawn to wherever they want the players to spawn.

**Comment by Thutmose** [comment]
this should no longer mess up on single player, and for servers, make sure to use /setworldspawn to where you want defuzz to put you.
