### ISSUE TITLE
Teleportation causes disconnect

### ISSUE THREAD

**Issue by whocallmetim** [Thutmose/ThutEssentials#15]
Whenever I try to teleport somewhere, using any of the teleport commands (/spawn, /home, etc), I get kicked off the server with the error 'Internal Server Error' ([latest.log output](https://pastebin.com/57gRfSsM))

I am then unable to reconnect until I restart the server. Minecraft informs me that there was an 'Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host.' ([latest.log output](https://pastebin.com/vP7vd66j))

I am running the recommended Forge version (1.12-14.21.1.2387) with ThutEssentials version 2.1.2 and ThutPermissions 2.0.0.

**Comment by Thutmose** [comment]
Hmm, I will look into that, it appears I may have forgotten to properly deal with an access transformer (I bet one of the other mods I test with provides the same access transformer, I suspect ThutCore does)

**Comment by Thutmose** [comment]
This is fixed in 2.1.3, which has just been uploaded to curseforge.
