### ISSUE TITLE
Missing: Claiming/Land commands?

### ISSUE THREAD

**Issue by SkullbocksDE** [Thutmose/ThutEssentials#17]
Hi thutmose,

I'm using version 2.1.3 of Thut Essentials and which command I'm using from the section Claiming ( thut.essentials.commands.land) the server yells:
Unknown command.

Is the section claiming not implemented? I've tried to create a team via "/createTeam Test". Then I thought 'maybe missing permissions' and I added "thut.essentials.commands.land.Create" to my group but I still encounter the same problem.

Kind regards

**Comment by Thutmose** [comment]
did you enable land in the config? land is disabled by default incase you are using some other land manager, and instead just use thutesentials for commands

**Comment by SkullbocksDE** [comment]
Hi thutmose,
one role back; my fault - you're right. It can't work with B:landEnabled=false *facepalm* :DD

**Comment by Thutmose** [comment]
no problem, I figured it might have been that

**Comment by SkullbocksDE** [comment]
After setting B:landEnabled=true I was able to use and test all commands from the land sections. It's working ^^
