### ISSUE TITLE
Server wont let player without the mod installed on their clients join

### ISSUE THREAD

**Issue by zackern** [Thutmose/ThutEssentials#21]
Hello!
This is probably the wrong place to post this issue but i will try.

I'm running FTB All the Mods 1.12.2. Forge version: 14.23.1.2568
I want to use ThutEssentials on the server but when it is installed the servern wont let the clients without it join.
`[18:15:20] [Netty Epoll Server IO #2/INFO] [FML]: Attempting connection with missing mods [mercurius_updater, thutessentials] at CLIENT
[18:15:50] [Netty Epoll Server IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException: null
[18:15:50] [Server thread/INFO]: zacker lost connection: Timed out
[18:15:50] [Server thread/INFO]: zacker left the game`
[The whole snippet from log](https://gist.github.com/zackern/2c11d57a614cce6faf86ef5a44402385)

**Comment by Thutmose** [comment]
forge reports the missing mods for the entire list of server only mods, your actual reason for not connecting was this:

NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException: null

**Comment by Thutmose** [comment]
example from another server:

```
14.01 15:02:25 [Server] User Authenticator #17/INFO UUID of player Thutmose is f1dacdfd-42d6-4af0-8234-b2f180ecd6a8
14.01 15:02:25 [Server] Netty Epoll Server IO #5/INFO [FML]: Client protocol version 2
14.01 15:02:25 [Server] Netty Epoll Server IO #5/INFO [FML]: Client attempting to join with 26 mods : minecraft@1.12.2,thutcore_compat@1.0,pokeplayer@1.12.2-1.0.1,pokecube_moves@4.5.1,pokecubeserverutils@1.5.2,jei@4.8.5.138,ftbu@4.2.4,pceditmod@1.10.2-2.0.0,mcp@9.42,journeymap@1.12.2-5.5.2,pokecube_adventures@6.14.9,FML@8.0.99.99,pokecube@6.35.3,foamfixcore@7.7.4,ftbl@4.2.5,thut_bling@2.0.2,pokecube_origin@4.5.1,pokecube_ml@0.1.0,pokecube_compat@1.0,foamfix@@VERSION@,pokecube_mobs@4.5.1,jeresources@0.8.6.28,thut_wearables@3.1.6,forge@14.23.1.2566,thuttech@6.0.11,thutcore@5.15.1
14.01 15:02:25 [Server] Netty Epoll Server IO #5/INFO [FML]: Attempting connection with missing mods [discordchat, enjinminecraftplugin, loot_crates, votifier, thutessentials] at CLIENT
14.01 15:02:25 [Server] Netty Epoll Server IO #5/INFO [journeymap]: CLIENT
14.01 15:02:26 [Server] Server thread/INFO [FML]: [Server thread] Server side modded connection established
14.01 15:02:26 [Connect] User Thutmose, IP 69.59.79.123
14.01 15:02:26 [Multicraft] Thutmose ran command Message of the Day
14.01 15:02:26 [Server] Server thread/INFO Thutmose joined the game
```
