### ISSUE TITLE
Ever the same Messages... Bug?

### ISSUE THREAD

**Issue by djdanby** [Thutmose/ThutEssentials#29]
SpongeForge Server 1.12.2

Ist that a Bug or what is the problem?

[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'listTeamAdmins' with an uppercase character - adjusting to 'listteamadmins'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'listTeamAdmins' with an uppercase character - adjusting to 'listteamadmins'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'createTeam' with an uppercase character - adjusting to 'createteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'createTeam' with an uppercase character - adjusting to 'createteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'deleteTeam' with an uppercase character - adjusting to 'deleteteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'deleteTeam' with an uppercase character - adjusting to 'deleteteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'editTeam' with an uppercase character - adjusting to 'editteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'teamInvite' with an uppercase character - adjusting to 'teaminvite'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'teamInvite' with an uppercase character - adjusting to 'teaminvite'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'teamInvites' with an uppercase character - adjusting to 'teaminvites'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'teamInvites' with an uppercase character - adjusting to 'teaminvites'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'joinTeam' with an uppercase character - adjusting to 'jointeam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'joinTeam' with an uppercase character - adjusting to 'jointeam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'kickFromTeam' with an uppercase character - adjusting to 'kickfromteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'kickFromTeam' with an uppercase character - adjusting to 'kickfromteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'leaveTeam' with an uppercase character - adjusting to 'leaveteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'leaveTeam' with an uppercase character - adjusting to 'leaveteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'listMembers' with an uppercase character - adjusting to 'listmembers'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'listMembers' with an uppercase character - adjusting to 'listmembers'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'landOwner' with an uppercase character - adjusting to 'landowner'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'landOwner' with an uppercase character - adjusting to 'landowner'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'removeTeamAdmin' with an uppercase character - adjusting to 'removeteamadmin'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'removeTeamAdmin' with an uppercase character - adjusting to 'removeteamadmin'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'renameTeam' with an uppercase character - adjusting to 'renameteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'renameTeam' with an uppercase character - adjusting to 'renameteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'setTeamAdmin' with an uppercase character - adjusting to 'setteamadmin'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'setTeamAdmin' with an uppercase character - adjusting to 'setteamadmin'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'myTeam' with an uppercase character - adjusting to 'myteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'myTeam' with an uppercase character - adjusting to 'myteam'
[m> [04:08:04] [Server thread/WARN] [Sponge]: Plugin 'thutessentials' is attempting to register command 'realName' with an uppercase character - adjusting to 'realname'

**Comment by Thutmose** [comment]
`Plugin 'thutessentials' ` Thut essentials is not a sponge plugin.

no bug on my end, not really a problem, just sponge renaming some commands because it doesn't differentiate between plugins and mods.

if you are using spongeforge though, there are probably plugins for it that do what this mod does, better than this mod does them.
