### ISSUE TITLE
a command for forcing players into teams

### ISSUE THREAD

**Issue by berendbro** [Thutmose/ThutEssentials#46]
As server admin I want to make players join a team also get added to a perms group. trying to do this with command blocks would be possible if we had a command that could force a player into a team.

this could be done by adding an optional parrameter [player] to OP version of the /joinTeam <team> command. This would result in /joinTeam <team> [player] where  the specified player username gets added to the give team.

an alternative could be /editteam <team > add <player>
but i got a feeling the current /editteam automatically targets the team you are in, not sure tho

this feature came from the discord channel.

**Comment by SlayerTheChikken** [comment]
I agree, maybe a sudo command as well

**Comment by Thutmose** [comment]
Next update will have /addtoteam <player> <team> which forces the player into that team.
