### ISSUE TITLE
Enhancement request for /motd

### ISSUE THREAD

**Issue by xenoflot** [Thutmose/ThutEssentials#5]
Hi,

The /motd command displays the vanilla or config motd as expected. Thank you!

Changing the MOTD still requires both editing a file (which requires downloading and reuploading) and then restarting the server. If possible, please add /motd <message> functionality to allow admins to change the MOTD without needing to manually edit the config and restart the server.

Cheers!

**Comment by Thutmose** [comment]
try using /teconfig motd [whatever you want motd to be here]

that should update it.

**Comment by xenoflot** [comment]
So it did. Thank you!

**Comment by Thutmose** [comment]
no problem, I made it so the configs for most of my mods with lots of configs can be edited ingame via similar commands

**Comment by xenoflot** [comment]
Coolio. As time and energy permits though, /motd <message> would be a nice addition :)

**Comment by xenoflot** [comment]
I really do appreciate the rapid addition of this feature!

**Comment by Thutmose** [comment]
it is in, that is what the latest release added.
