### ISSUE TITLE
1.12.2-2.2.16 Server crash java.lang.NullPointerException: Ticking player

### ISSUE THREAD

**Issue by jusitnboggs** [Thutmose/ThutEssentials#50]
#### Issue Description:
FUGaming Mod Pack Maker.

Players on my server found out that when using a Glacial Precipitator from TE
when you click the next or back buttons it will crash the server (the buttons would still do their job)

Crash Log https://pastebin.com/Phn7fNq8
#### (What happens:
Server crashes

#### What you expected to happen:
snowballs would switch to snow blocks

#### Steps to reproduce:

1. click buttons

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.
- TE: 1.12.2-5.5.3.41
- Thutessentials: 2.2.16
- Minecraft: 1.12.2
- Forge: 14.23.5.2815

**Comment by jusitnboggs** [comment]
Crash Log https://pastebin.com/Phn7fNq8

**Comment by Thutmose** [comment]
The fix for #52 should also fix this one.
