### ISSUE TITLE
1.15.2 /del_home or /del_warp errors in game 

### ISSUE THREAD

**Issue by captcookie** [Thutmose/ThutEssentials#65]
#### What happens:
Failure to delete homes and warps when using the proper commands

Success deleting homes and warps is what I would expect to happen.
Steps:
1.create homes then use /del_home name
2. read message, will say error

____
- Thutessentials: 
- Minecraft: 1.15.2
- Forge: 31.1.12

I did find a work around by going into the server files and finding the world folder then thutessentials to manually delete all saved homes

**Comment by Thutmose** [comment]
3.0.5 has been uploaded which should fix this.
