### ISSUE TITLE
chatFormat

### ISSUE THREAD

**Issue by mcedj** [Thutmose/ThutEssentials#66]
I am trying to personalize the chatFormat in the thutessentials.cfg file. However I haven't seen any changes.
Do I have to execute a command or something else in order to aply them?
Thanks

**Comment by Thutmose** [comment]
you need to set forceChatFormat to true as well as chatTweaks for that to work iirc, it might also need a server reboot for it to apply

**Comment by mcedj** [comment]
Thank you, it worked, I didn't see that bit.
