### ISSUE TITLE
 thutessentials.tp.tele_init and thutessentials.tp.standstill not being used in server config

### ISSUE THREAD

**Issue by PsychoTechV4** [Thutmose/ThutEssentials#71]
#### Issue Description:
when running a tp related command it popup

#### What happens:
tp related commands

#### What you expected to happen:
to say 
You must remain still to teleport!
Please remain stationary while the teleport occurs.

#### Steps to reproduce:
1: install en_us.json to a 1.14.4 server
2: run any tp related command 

#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutessentials: 1.14.4-3.0.7
- Minecraft: 1.14.4
- Forge: 1.14.4-28.2.0

**Comment by Thutmose** [comment]
can you confim if this issue occurs in 3.0.9+?

**Comment by Psych0Tech** [comment]
https://i.imgur.com/ViuwCLK.png

**Comment by PsychoTechV4** [comment]
1.14.4-3.0.9 is still doing it
![image](https://user-images.githubusercontent.com/62632194/77659806-c064c200-6f35-11ea-8c19-ad9eeeda9f1e.png)

**Comment by CpHarding** [comment]
issue is fixed by adding the mod to the client, ideally should just work serverside though.

**Comment by Thutmose** [comment]
this should be fixed in 3.0.11, which was just uploaded.
