### ISSUE TITLE
lang file not working with 1.14.4 version

### ISSUE THREAD

**Issue by Alkiasan** [Thutmose/ThutEssentials#73]
Whenever running any commands inside of this mod, whether it be teleport or balance, it seems to output strings such as thutessentials.tpa.requested instead of "Teleport request sent" . I've tried removing all resource packs, adding the lang from the mod to a resource pack, and neither of those has worked.

#### Steps to reproduce:

1. run command (e.g. ./tpa Alkiasan
2. Recieve result
3. https://i.imgur.com/gO3W89u.png
____
#### Affected Versions:

- Thutessentials: 1.14.4-3.0.9
- Minecraft: 1.14.4
- Forge: 28.2.0
- Aquaculture 2.0.7
- AutoRegLib- 1.4-35
- CosmeticArmorReworked v1b
- IBEEditor 1.0.2
- MorePlayerModels 12Dec19 SNAPSHOT
- PGA 1.1.0.1
- Quark r2.0-212
- WorldProtector- 1.14.4-V2
- YAMDA-4.0.1
- cfm-7.0.0-pre15
- cosmeticbeds-FORGE-2.0.0.1
- mgui 1.2.0
- sisser 1.1
- swingthroughgrass 1.3.2
- tetra 1.26.0
- thutperms-3.0.5
- worldediit-forge-7.0.1

**Comment by Thutmose** [comment]
did you try putting the lang file from the mod in the config folder? ie in config/thutessentials?

**Comment by Alkiasan** [comment]
Thank you! That fixed it!
