### ISSUE TITLE
Server Crash from land claming ?

### ISSUE THREAD

**Issue by IchigoGames** [Thutmose/ThutEssentials#77]
#### Issue Description:
not sure how it happens it but server crashed 
and i got this crash report 

#### What happens:
crashed
crash report https://pastebin.com/0FpPE4hm

#### What you expected to happen:
Not to crash

#### Steps to reproduce:

1. i think it has to do with claiming

#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutessentials:-1.15.2-3.0.10 
- Minecraft: 1.15.2
- Forge:31.1.36

**Comment by Thutmose** [comment]
ahha, this is a compatiblity issue, I will look into the fix, it is compatiblity between the land claiming system and whichever mod contains "com.buuz135.industrial", do you have any idea which that is?

It will be some mod that adds something that places blocks

**Comment by IchigoGames** [comment]
ah ya that would be industrial foregoing block placer https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing

**Comment by IchigoGames** [comment]
using industrial-foregoing-1.15.2-2.2.2-28d4a81

**Comment by Thutmose** [comment]
I see, their fakeplayer isn't actually a forge fakeplayer, so it isn't being detected as such

**Comment by Thutmose** [comment]
or nevermine, it is a fakeplayer, let me look into what is going wrong here

**Comment by Thutmose** [comment]
this should be fixed in 3.0.11, which was just uploaded.
