### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by Osprey4444** [Thutmose/ThutEssentials#78]
## Read and then Delete this section - If this is in your bug report, it will be closed.
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

Hello,

I installed ThutPerms as I was wanting a permissions system on my 1.14.4 Modded Server to match my other 1.12.2 one's. But it didn't seem to work.

So, I installed ThutEssentials alongside it, but ThutEssentials didn't work either.

#### What happens:

Nothing happens.

#### What you expected to happen:

For it to work.

#### Steps to reproduce:

1. Use Enigmatica 4 Modpack.
2. Install ThutPerms and ThutEssentials.
3. Realize it doesn't work.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutessentials: 1.14.4-3.0.9
- ThutPerms: 1.14.4-3.0.5
- Minecraft: 1.14.4
- Forge-1.14.4-28.2.3

**Comment by Thutmose** [comment]
closing issue that tells me to close it on line 1
