### ISSUE TITLE
Dimension Wild Lvls

### ISSUE THREAD

**Issue by GogaTheAcute** [Thutmose/ThutEssentials#86]
I feel as Other dimentions shouldn't have a low level spawn Center.

Going to ultra space and finding lvl 5 ultra beasts definitely felt underwhelming and getting all the treasure without any real threat also pulled away from my experience. The minimum lvl should be around 20-30.

The dimentions should be a mid/late-game feature, especially ultra space.

**Comment by Thutmose** [comment]
this is on the wrong tracker, can you re-make it here: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues
