### ISSUE TITLE
Wild Evolved Forms

### ISSUE THREAD

**Issue by GogaTheAcute** [Thutmose/ThutEssentials#87]
There are too many evolved wild pokemon away from spawn. In the games you can always find high levelled stage 1 pokemon in the late game. In the games some evolved forms are quite rare in the wild(gyarados, flygon etc).

It would add to the experience of wonder in seeing such pokemon if more pokemon were earlier stages int the wild.

Would be cool if wild pokemon didn't follow the evolution chart based on levels and evolved forms were a bit rarer even if after you catch them and evolve once they evolve.

**Comment by Thutmose** [comment]
this is on wrong tracker, can you re-make the issue here please: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues
