### ISSUE TITLE
[1.15.2] Server crash Ticking entity at thut.essentials.land.LandEventsHandler

### ISSUE THREAD

**Issue by IchigoGames** [Thutmose/ThutEssentials#90]
#### Issue Description:
not sure whats doing it but it seems to be this mod after looking at crash report

Ticking entity at thut.essentials.land.LandEventsHandler$EntityEventHandler.mobGriefing
something to do with it trying to stop mob Griefing in some ones claim could have something to do with Griefing being disabled by game rule on server ?

https://pastebin.com/jD1U9fyp

#### What happens:
server crashed

#### What you expected to happen:
server not to crash

#### Steps to reproduce:
not sure was not on when it happned
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutessentials:-1.15.2-3.0.14 
- Minecraft: 1.15.2
- Forge:31.1.77

**Comment by IchigoGames** [comment]
got more info on it look like some one got shot at by a ghast as soon as they entered the nether but they did not have a claim in nether so idk its crashing but it is.

**Comment by Thutmose** [comment]
I have this fixed for next update, I wil lget that pushed asap

**Comment by Thutmose** [comment]
fixed in 3.0.15, if it re-occurs please comment here so I can re-open the report, or make a new one
