### ISSUE TITLE
Professir Cedar not want to trade

### ISSUE THREAD

**Issue by Shadowknight2017** [Thutmose/ThutEssentials#97]
#### Issue Description:
Professir Cedar not want to trade

#### What happens:
you click on him does nothing some time say he does not want to battle

#### What you expected to happen:
can trade 

#### Steps to reproduce:

1.click on Professir Cedar
2.
3.
...

____

**Comment by Thutmose** [comment]
this seems to be a pokecube issue, it should probably be here: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues
